name: pptam
channels:
  - conda-forge
  - r
dependencies:
  - python=3.8
  - pip
  - r-essentials
  - anaconda
  - jupyter
  - pip:
      - requests
      - locust
      - psutil
      - influxdb-client
