version: '3.2'

services:
  db:
    image: "postgres:alpine"
    command: postgres -c 'max_connections=200'
    restart: always
    environment:
      POSTGRES_DB: messages
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: un!bz4r3Gis
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
     image: dpage/pgadmin4
     restart: always
     environment:
       PGADMIN_DEFAULT_EMAIL: sbhuiyan@unibz.it
       PGADMIN_DEFAULT_PASSWORD: admin1234
       PGADMIN_LISTEN_PORT: 80
     ports:
       - "80:80"
     volumes:
       - pgadmin-data:/var/lib/pgadmin

  volumes:
    db-data:
    pgadmin-data: