version: "3"
services:
  #  rabbitmq:
  #    image: rabbitmq:management
  #    ports:
  #      - 5672:5672
  #      - 15672:15672
  #      #      
  # kafka:
  #   container_name: kafka
  #   image: spotify/kafka:latest
  #   ports:
  #    - 2181:2181
  #    - 9092:9092
  #     #     
  #  zipkin:
  #    image: openzipkin/zipkin
  #    ports:
  #      - 9411:9411
  #      #      
  redis:
    image: redis
    ports:
      - 6379:6379
    deploy:
      placement:
        constraints:
          - node.hostname == socks2

  ts-ui-dashboard:
    image: codewisdom/ts-ui-dashboard:0.0.3
    restart: always
    ports:
      - 8080:8080
    deploy:
      placement:
        constraints:
          - node.hostname == socks2
          
  ts-auth-service:
    image: codewisdom/ts-auth-service:0.0.3
    restart: always
    ports:
      - 12340:12340
    deploy:
      placement:
        constraints:
          - node.hostname == socks2
          
  ts-auth-mongo:
    image: mongo
    deploy:
      placement:
        constraints:
          - node.hostname == socks2
          
  ts-user-service:
    image: codewisdom/ts-user-service:0.0.3
    restart: always
    ports:
      - 12342:12342
    deploy:
      placement:
        constraints:
          - node.hostname == socks2
          
  ts-user-mongo:
    image: mongo
    deploy:
      placement:
        constraints:
          - node.hostname == socks2
          
  ts-verification-code-service:
    image: codewisdom/ts-verification-code-service:0.0.3
    restart: always
    ports:
      - 15678:15678
    deploy:
      placement:
        constraints:
          - node.hostname == socks2
          
  ts-account-mongo:
    image: mongo
    deploy:
      placement:
        constraints:
          - node.hostname == socks2
          
  ts-route-service:
    image: codewisdom/ts-route-service:0.0.3
    restart: always
    ports:
      - 11178:11178
    deploy:
      placement:
        constraints:
          - node.hostname == socks2
          
  ts-route-mongo:
    image: mongo
    deploy:
      placement:
        constraints:
          - node.hostname == socks2
          
  ts-contacts-service:
    image: codewisdom/ts-contacts-service:0.0.3
    restart: always
    ports:
      - 12347:12347
    deploy:
      placement:
        constraints:
          - node.hostname == socks2
          
  ts-contacts-mongo:
    image: mongo
    deploy:
      placement:
        constraints:
          - node.hostname == socks2
          
  ts-order-service:
    image: codewisdom/ts-order-service:0.0.3
    restart: always
    ports:
      - 12031:12031
    deploy:
      placement:
        constraints:
          - node.hostname == socks2
          
  ts-order-mongo:
    image: mongo
    deploy:
      placement:
        constraints:
          - node.hostname == socks2
          
  ts-order-other-service:
    image: codewisdom/ts-order-other-service:0.0.3
    restart: always
    ports:
      - 12032:12032
    deploy:
      placement:
        constraints:
          - node.hostname == socks2
          
  ts-order-other-mongo:
    image: mongo
    deploy:
      placement:
        constraints:
          - node.hostname == socks2
          
  ts-config-service:
    image: codewisdom/ts-config-service:0.0.3
    restart: always
    ports:
      - 15679:15679
    deploy:
      placement:
        constraints:
          - node.hostname == socks2
          
  ts-config-mongo:
    image: mongo
    deploy:
      placement:
        constraints:
          - node.hostname == socks2
          
  ts-station-service:
    image: codewisdom/ts-station-service:0.0.3
    restart: always
    ports:
      - 12345:12345
    deploy:
      placement:
        constraints:
          - node.hostname == socks2
          
  ts-station-mongo:
    image: mongo
    deploy:
      placement:
        constraints:
          - node.hostname == socks2
          
  ts-train-service:
    image: codewisdom/ts-train-service:0.0.3
    restart: always
    ports:
      - 14567:14567
    deploy:
      placement:
        constraints:
          - node.hostname == socks2
          
  ts-train-mongo:
    image: mongo
    deploy:
      placement:
        constraints:
          - node.hostname == socks2
          
  ts-travel-service:
    image: codewisdom/ts-travel-service:0.0.3
    restart: always
    ports:
      - 12346:12346
    deploy:
      placement:
        constraints:
          - node.hostname == socks2
          
  ts-travel-mongo:
    image: mongo
    deploy:
      placement:
        constraints:
          - node.hostname == socks2
          
  ts-travel2-service:
    image: codewisdom/ts-travel2-service:0.0.3
    restart: always
    ports:
      - 16346:16346
    deploy:
      placement:
        constraints:
          - node.hostname == socks2
          
  ts-travel2-mongo:
    image: mongo
    deploy:
      placement:
        constraints:
          - node.hostname == socks2
          
  ts-preserve-service:
    image: codewisdom/ts-preserve-service:0.0.3
    restart: always
    ports:
      - 14568:14568
    deploy:
      placement:
        constraints:
          - node.hostname == socks2
          
  ts-preserve-other-service:
    image: codewisdom/ts-preserve-other-service:0.0.3
    restart: always
    ports:
      - 14569:14569
    deploy:
      placement:
        constraints:
          - node.hostname == socks2
          
  ts-basic-service:
    image: codewisdom/ts-basic-service:0.0.3
    restart: always
    ports:
      - 15680:15680
    deploy:
      placement:
        constraints:
          - node.hostname == socks2
          
  ts-ticketinfo-service:
    image: codewisdom/ts-ticketinfo-service:0.0.3
    restart: always
    ports:
      - 15681:15681
    deploy:
      placement:
        constraints:
          - node.hostname == socks2
          
  ts-price-service:
    image: codewisdom/ts-price-service:0.0.3
    restart: always
    ports:
      - 16579:16579
    deploy:
      placement:
        constraints:
          - node.hostname == socks2
          
  ts-price-mongo:
    image: mongo
    deploy:
      placement:
        constraints:
          - node.hostname == socks2
          
  ts-notification-service:
    image: codewisdom/ts-notification-service:0.0.3
    restart: always
    ports:
      - 17853:17853
    deploy:
      placement:
        constraints:
          - node.hostname == socks2
          
  ts-security-service:
    image: codewisdom/ts-security-service:0.0.3
    restart: always
    ports:
      - 11188:11188
    deploy:
      placement:
        constraints:
          - node.hostname == socks2
          
  ts-security-mongo:
    image: mongo
    deploy:
      placement:
        constraints:
          - node.hostname == socks2
          
  ts-inside-payment-service:
    image: codewisdom/ts-inside-payment-service:0.0.3
    restart: always
    ports:
      - 18673:18673
    deploy:
      placement:
        constraints:
          - node.hostname == socks2
          
  ts-inside-payment-mongo:
    image: mongo
    deploy:
      placement:
        constraints:
          - node.hostname == socks2
          
  ts-execute-service:
    image: codewisdom/ts-execute-service:0.0.3
    restart: always
    ports:
      - 12386:12386
    deploy:
      placement:
        constraints:
          - node.hostname == socks2
          
  ts-payment-service:
    image: codewisdom/ts-payment-service:0.0.3
    restart: always
    ports:
      - 19001:19001
    deploy:
      placement:
        constraints:
          - node.hostname == socks2
          
  ts-payment-mongo:
    image: mongo
    deploy:
      placement:
        constraints:
          - node.hostname == socks2
          
  ts-rebook-service:
    image: codewisdom/ts-rebook-service:0.0.3
    restart: always
    ports:
      - 18886:18886
    deploy:
      placement:
        constraints:
          - node.hostname == socks2
          
  ts-rebook-mongo:
    image: mongo
    deploy:
      placement:
        constraints:
          - node.hostname == socks2
          
  ts-cancel-service:
    image: codewisdom/ts-cancel-service:0.0.3
    restart: always
    ports:
      - 18885:18885
    deploy:
      placement:
        constraints:
          - node.hostname == socks2
          
  ts-assurance-service:
    image: codewisdom/ts-assurance-service:0.0.3
    restart: always
    ports:
      - 18888:18888
    deploy:
      placement:
        constraints:
          - node.hostname == socks2
          
  ts-assurance-mongo:
    image: mongo
    deploy:
      placement:
        constraints:
          - node.hostname == socks2
          
  ts-seat-service:
    image: codewisdom/ts-seat-service:0.0.3
    restart: always
    ports:
      - 18898:18898
    deploy:
      placement:
        constraints:
          - node.hostname == socks2
          
  ts-travel-plan-service:
    image: codewisdom/ts-travel-plan-service:0.0.3
    restart: always
    ports:
      - 14322:14322
    deploy:
      placement:
        constraints:
          - node.hostname == socks2
          
  ts-ticket-office-service:
    image: codewisdom/ts-ticket-office-service:0.0.3
    restart: always
    ports:
      - 16108:16108
    deploy:
      placement:
        constraints:
          - node.hostname == socks2
          
  ts-ticket-office-mongo:
    image: mongo
    deploy:
      placement:
        constraints:
          - node.hostname == socks2
          
  ts-news-service:
    image: codewisdom/ts-news-service:0.0.3
    restart: always
    ports:
      - 12862:12862
    deploy:
      placement:
        constraints:
          - node.hostname == socks2
          
  ts-news-mongo:
    image: mongo
    deploy:
      placement:
        constraints:
          - node.hostname == socks2
          
  ts-voucher-mysql:
    image: mysql
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    deploy:
      placement:
        constraints:
          - node.hostname == socks2
          
  ts-voucher-service:
    image: codewisdom/ts-voucher-service:0.0.3
    restart: always
    ports:
      - 16101:16101
    depends_on:
      - ts-voucher-mysql
    volumes:
      - /var/lib/mysql
    deploy:
      placement:
        constraints:
          - node.hostname == socks2
          
  ts-food-map-service:
    image: codewisdom/ts-food-map-service:0.0.3
    restart: always
    ports:
      - 18855:18855
    deploy:
      placement:
        constraints:
          - node.hostname == socks2
          
  ts-food-map-mongo:
    image: mongo
    deploy:
      placement:
        constraints:
          - node.hostname == socks2
          
  ts-route-plan-service:
    image: codewisdom/ts-route-plan-service:0.0.3
    restart: always
    ports:
      - 14578:14578
    deploy:
      placement:
        constraints:
          - node.hostname == socks2
          
  ts-food-service:
    image: codewisdom/ts-food-service:0.0.3
    restart: always
    ports:
      - 18856:18856
    deploy:
      placement:
        constraints:
          - node.hostname == socks2
          
  ts-consign-service:
    image: codewisdom/ts-consign-service:0.0.3
    restart: always
    ports:
      - 16111:16111
    deploy:
      placement:
        constraints:
          - node.hostname == socks2
          
  ts-consign-mongo:
    image: mongo
    deploy:
      placement:
        constraints:
          - node.hostname == socks2
          
  ts-consign-price-service:
    image: codewisdom/ts-consign-price-service:0.0.3
    restart: always
    ports:
      - 16110:16110
    deploy:
      placement:
        constraints:
          - node.hostname == socks2
          
  ts-consign-price-mongo:
    image: mongo
    deploy:
      placement:
        constraints:
          - node.hostname == socks2
          
  ts-food-mongo:
    image: mongo
    deploy:
      placement:
        constraints:
          - node.hostname == socks2
          
  ts-admin-basic-info-service:
    image: codewisdom/ts-admin-basic-info-service:0.0.3
    restart: always
    ports:
      - 18767:18767
    deploy:
      placement:
        constraints:
          - node.hostname == socks2
          
  ts-admin-order-service:
    image: codewisdom/ts-admin-order-service:0.0.3
    restart: always
    ports:
      - 16112:16112
    deploy:
      placement:
        constraints:
          - node.hostname == socks2
          
  ts-admin-route-service:
    image: codewisdom/ts-admin-route-service:0.0.3
    restart: always
    ports:
      - 16113:16113
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    deploy:
      placement:
        constraints:
          - node.hostname == socks2
          
  ts-admin-travel-service:
    image: codewisdom/ts-admin-travel-service:0.0.3
    restart: always
    ports:
      - 16114:16114
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    deploy:
      placement:
        constraints:
          - node.hostname == socks2
          
  ts-admin-user-service:
    image: codewisdom/ts-admin-user-service:0.0.3
    restart: always
    ports:
      - 16115:16115
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    deploy:
      placement:
        constraints:
          - node.hostname == socks2
          
  jaeger:
    image: jaegertracing/all-in-one:1.15
    ports:
      - 16686:16686
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    deploy:
      placement:
        constraints:
          - node.hostname == socks2
          
